version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: settlement_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - settlement-network

  backend:
    build: ./backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: settlement_db
      JWT_SECRET: your-secret-key-here
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - settlement-network
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - settlement-network

volumes:
  postgres_data:

networks:
  settlement-network:
    driver: bridge 